EdgeOfTheEmpire/Models/Character.cs
using EdgeOfTheEmpire.Entities;
using System;
using System.Collections.Generic;

namespace EdgeOfTheEmpire.Models
{
    public class Character
    {
        private InitialCharacter initial;
        private IList<CharacterSpecializationAdvance> specializationAdvances;
        private IList<CharacterSkillAdvance> skillAdvance;
        private IList<CharacterSignatureAbilityAdvance> signatureAbilityAdvance;
        private IList<CharacterBattleScarAdvance> battleScarAdvance;

        public Character(InitialCharacter initial, 
            IList<CharacterSpecializationAdvance> specializationAdvances,
            IList<CharacterSkillAdvance> skillAdvance,
            IList<CharacterSignatureAbilityAdvance> signatureAbilityAdvance,
            IList<CharacterBattleScarAdvance> battleScarAdvance

            )
        {
            this.initial = initial;
            this.specializationAdvances = specializationAdvances;
            this.skillAdvance = skillAdvance;
            this.signatureAbilityAdvance = signatureAbilityAdvance;
            this.battleScarAdvance = battleScarAdvance;
        }
        public String Name => initial.Name;
        public string Race => initial.Race;

        public int Brawn => initial.Brawn;
        public int Agility => initial.Agility;
        public int Intelligence => initial.Intelligence;
        public int Cunning => initial.Cunning;
        public int Willpower => initial.Willpower;
        public int Presence => initial.Presence;


    }
}

EdgeOfTheEmpire/ViewModels/CharacterViewModel.cs
using EdgeOfTheEmpire.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EdgeOfTheEmpire.ViewModels
{
    public class CharacterViewModel
    {
        public Character Character { get; set; }
        
    }
}

EdgeOfTheEmpire/Controllers/CharacterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EdgeOfTheEmpire.Models;
using EdgeOfTheEmpire.ViewModels;
using EdgeOfTheEmpire.Entities;
using EdgeOfTheEmpire.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EdgeOfTheEmpire.Controllers
{
    public class CharacterController : Controller
    {
        private ICharacterRepository characterRepository;
        public CharacterController(ICharacterRepository characterRepository)
        {
            this.characterRepository= characterRepository;
        }
        // GET: /<controller>/
        public IActionResult Index(string characterName)
        {
            Character character = characterRepository.GetCharacter(characterName);                       
            CharacterViewModel a = new CharacterViewModel() { Character = character };
            return View(a);
        }

        public IActionResult List()
        {
            return View(characterRepository.Characters);
        }

        public IActionResult AddCharacter()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCharacter(InitialCharacter character)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            characterRepository.AddCharacter(character);
            return View();
        }

        public IActionResult AddBattleScarAdvance()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddBattleScarAdvance(CharacterBattleScarAdvance battleScarAdvance)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            characterRepository.AddBattleScarAdvance(battleScarAdvance);
            return View();
        }

        public IActionResult AddSkillAdvance()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddSkillAdvance(CharacterSkillAdvance skillAdvance)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            characterRepository.AddSkillAdvance(skillAdvance);
            return View();
        }

        public IActionResult AddSpecializationAdvance()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddSpecializationAdvance(CharacterSpecializationAdvance specializationAdvance)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            characterRepository.AddSpecializationAdvance(specializationAdvance);
            return View();
        }

        public IActionResult AddSignatureAbility()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSignatureAbility(CharacterSignatureAbility signatureAbility)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            characterRepository.AddSignatureAbility(signatureAbility);
            return View();
        }


        public IActionResult AddSignatureAbilityAdvance()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddSignatureAbilityAdvance(CharacterSignatureAbilityAdvance signatureAbilityAdvance)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            characterRepository.AddSignatureAbilityAdvance(signatureAbilityAdvance);
            return View();
        }



        public IActionResult AddSpecialization()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSpecialization(Entities.CharacterSpecialization specialization)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            characterRepository.AddSpecialization(specialization);
            return View();
        }
    }
}

EdgeOfTheEmpire/Views/Character/AddBattleScarAdvance.cshtml
@model EdgeOfTheEmpire.Entities.CharacterBattleScarAdvance

<form asp-action="AddBattleScarAdvance" method="post" class="form-horizontal" role="form">
    <div class="form-group">
        <label asp-for="Talent" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Talent" class="form-control" />
            <span asp-validation-for="Talent" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Add battle scar" />
        </div>
    </div>
</form>

EdgeOfTheEmpire/Views/Character/AddCharacter.cshtml
@model EdgeOfTheEmpire.Entities.InitialCharacter

<form asp-action="AddCharacter" method="post" class="form-horizontal" role="form">

    <div class="form-group">
        <label asp-for="Name" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Player" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Player" class="form-control" />
            <span asp-validation-for="Player" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Race" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Race" class="form-control" />
            <span asp-validation-for="Race" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Brawn" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Brawn" class="form-control" />
            <span asp-validation-for="Brawn" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Agility" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Agility" class="form-control" />
            <span asp-validation-for="Agility" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Intelligence" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Intelligence" class="form-control" />
            <span asp-validation-for="Intelligence" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Cunning" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Cunning" class="form-control" />
            <span asp-validation-for="Cunning" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Willpower" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Willpower" class="form-control" />
            <span asp-validation-for="Willpower" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Presence" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Presence" class="form-control" />
            <span asp-validation-for="Presence" class="text-danger"></span>
        </div>
    </div>  
     
    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="AddCharacter" />
        </div>
    </div>
</form>

EdgeOfTheEmpire/Views/Character/AddSignatureAbility.cshtml
@model EdgeOfTheEmpire.Entities.CharacterSignatureAbility

<form asp-action="AddSpecialization" method="post" class="form-horizontal" role="form">
    <div class="form-group">
        <label asp-for="SignatureAbility" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="SignatureAbility" class="form-control" />
            <span asp-validation-for="SignatureAbility" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Add specialization" />
        </div>
    </div>
</form>

EdgeOfTheEmpire/Views/Character/AddSignatureAbilityAdvance.cshtml
@model EdgeOfTheEmpire.Entities.CharacterSignatureAbilityAdvance

<form asp-action="AddSignatureAbilityAdvance" method="post" class="form-horizontal" role="form">
    <div class="form-group">
        <label asp-for="SignatureAbility" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="SignatureAbility" class="form-control" />
            <span asp-validation-for="SignatureAbility" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Row" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Row" class="form-control" />
            <span asp-validation-for="Row" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Column" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Column" class="form-control" />
            <span asp-validation-for="Column" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Improve signature ability" />
        </div>
    </div>
</form>

EdgeOfTheEmpire/Views/Character/AddSkillAdvance.cshtml
@model EdgeOfTheEmpire.Entities.CharacterSkillAdvance

<form asp-action="AddSkillAdvance" method="post" class="form-horizontal" role="form">
    <div class="form-group">
        <label asp-for="Skill" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Skill" class="form-control" />
            <span asp-validation-for="Skill" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Rank" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Rank" class="form-control" />
            <span asp-validation-for="Rank" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Improve skill" />
        </div>
    </div>
</form>

EdgeOfTheEmpire/Views/Character/AddSpecialization.cshtml
@model EdgeOfTheEmpire.Entities.CharacterSpecialization

<form asp-action="AddSpecialization" method="post" class="form-horizontal" role="form">
    <div class="form-group">
        <label asp-for="Specialization" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Specialization" class="form-control" />
            <span asp-validation-for="Specialization" class="text-danger"></span>
        </div>
    </div>
   
    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Add specialization" />
        </div>
    </div>

</form>

EdgeOfTheEmpire/Views/Character/AddSpecializationAdvance.cshtml
@model EdgeOfTheEmpire.Entities.CharacterSpecializationAdvance

<form asp-action="AddSpecializationAdvance" method="post" class="form-horizontal" role="form">
    <div class="form-group">
        <label asp-for="Specialization" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Specialization" class="form-control" />
            <span asp-validation-for="Specialization" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Row" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Row" class="form-control" />
            <span asp-validation-for="Row" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Column" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Column" class="form-control" />
            <span asp-validation-for="Column" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Improve specialization" />
        </div>
    </div>
</form>

EdgeOfTheEmpire/Views/Character/Index.cshtml
@model EdgeOfTheEmpire.ViewModels.CharacterViewModel;

<div class="container">
    <h1>@Model.Character.Name</h1>
    <p>@Model.Character.Race</p>
    <div class="col-md-2">Brawn</div>
    <div class="col-md-2">Agility</div>
    <div class="col-md-2">Intelligence</div>
    <div class="col-md-2">Cunning</div>
    <div class="col-md-2">Willpower</div>
    <div class="col-md-2">Presence</div>

    <div class="col-md-2">@Model.Character.Brawn</div>
    <div class="col-md-2">@Model.Character.Agility</div>
    <div class="col-md-2">@Model.Character.Intelligence</div>
    <div class="col-md-2">@Model.Character.Cunning</div>
    <div class="col-md-2">@Model.Character.Willpower</div>
    <div class="col-md-2">@Model.Character.Presence</div>
</div>

<div class="container">
    <ul>
        <li><a asp-controller="Character" asp-action="AddSpecialization">Add Specialization</a></li>
        <li><a asp-controller="Character" asp-action="AddSpecializationAdvance">Improve Specialization</a></li>
        <li><a asp-controller="Character" asp-action="AddSkillAdvance">Improve Skill</a></li>
        <li><a asp-controller="Character" asp-action="AddSignatureAbility">Add Signature Ability</a></li>
        <li><a asp-controller="Character" asp-action="AddSignatureAbilityAdvance">Improve Signature Ability</a></li>
        <li><a asp-controller="Character" asp-action="AddBattleScarAdvance">Add BattleScar Skill</a></li>
    </ul>
       
</div>

EdgeOfTheEmpire/Views/Character/List.cshtml
@model IEnumerable<EdgeOfTheEmpire.Models.Character>

<h2>Characters</h2>
<div class="container">
    @foreach (var character in Model)
    {
        <h2>
            <a asp-controller="Character" asp-action="Index" asp-route-characterName="@character.Name">@character.Name</a>
        </h2>
    }
</div>

<div class="container">
    <a asp-controller="Character" asp-action="AddCharacter">Add new Character</a>
</div>