EdgeOfTheEmpire/Controllers/CareerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EdgeOfTheEmpire.Models;
using EdgeOfTheEmpire.ViewModels;
using EdgeOfTheEmpire.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EdgeOfTheEmpire.Controllers
{
    public class CareerController : Controller
    {
        private readonly IStaticDataRepository staticDataRepository;
        public CareerController(IStaticDataRepository staticDataRepository)
        {
            this.staticDataRepository = staticDataRepository;
        }
        // GET: /<controller>/
        public IActionResult List()
        {
            ViewBag.Title = "Careers";
            return View(staticDataRepository.GetCarreers());
        }

        public IActionResult Index(string career)
        {
            Career theCareer = staticDataRepository.GetCareer(career);
            IEnumerable<Skill> careerSkills = staticDataRepository.GetCareerSkills(theCareer);
            IEnumerable<Specialization> careerSpecializations = staticDataRepository.GetCareerSpecializations(theCareer);

            CareerInfoViewModel careerInfo = new CareerInfoViewModel()
            {
                Career = theCareer,
                Skills = careerSkills,
                Specializations = careerSpecializations
            };

            return View(careerInfo);
        }
    }
}

EdgeOfTheEmpire/Controllers/SkillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EdgeOfTheEmpire.Models;
using EdgeOfTheEmpire.ViewModels;
using EdgeOfTheEmpire.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EdgeOfTheEmpire.Controllers
{
    public class SkillController : Controller
    {
        IStaticDataRepository staticDataRepository;
        public SkillController(IStaticDataRepository staticDataRepository)
        {
            this.staticDataRepository = staticDataRepository;
        }
        // GET: /<controller>/
        public IActionResult Index(string skill)
        {
            Skill theSkill = staticDataRepository.GetSkill(skill);
            IList<Career> careers = staticDataRepository.GetCareersWithSkill(theSkill);
            IList<Specialization> specializations = staticDataRepository.GetSpecializationsWithSkill(theSkill);
            var vm = new SkillViewModel() { Skill = theSkill, Careers = careers, Specializations = specializations };
            return View(vm);
        }
        public IActionResult List()
        {
            return View(staticDataRepository.GetSkills());
        }
    }
}

EdgeOfTheEmpire/Controllers/TalentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EdgeOfTheEmpire.Models;
using EdgeOfTheEmpire.ViewModels;
using EdgeOfTheEmpire.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EdgeOfTheEmpire.Controllers
{
    public class TalentController : Controller
    {
        private readonly IStaticDataRepository staticDataRepository;

        public TalentController(IStaticDataRepository staticDataRepository)
        {
            this.staticDataRepository = staticDataRepository;
        }

        // GET: /<controller>/
        public IActionResult Index(string talentName)
        {
            Talent talent = staticDataRepository.GetTalent(talentName);
            var specializations = staticDataRepository.GetSpecializationsWithTalent(talent);
            var vm = new TalentInfoViewModel() { Talent = talent, Specializations = specializations };
            return View(vm);
        }

        public IActionResult List()
        {
            return View(staticDataRepository.GetTalents());
        }
    }
}

EdgeOfTheEmpire/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edge of the empire</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Character" asp-action="List">Characters</a></li>
                    <li><a asp-controller="Career" asp-action="List">Careers</a></li>
                    <li><a asp-controller="Specialization" asp-action="List">Specializations</a></li>
                    <li><a asp-controller="Skill" asp-action="List">Skills</a></li>
                    <li><a asp-controller="Talent" asp-action="List">Talents</a></li>                    
                </ul>
                
            </div>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>