EdgeOfTheEmpire/Models/Specialization.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EdgeOfTheEmpire.Models
{
    public class Specialization
    {
        public Specialization(int id, string name, Career career)
        {
            SpecializationId = id;
            SpecializationName = name;
            Career = career;        
        }

        public int SpecializationId { get; set; }
        public Career Career { get; set; }
        public string SpecializationName { get; set; }

    }
}

EdgeOfTheEmpire/Controllers/SkillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EdgeOfTheEmpire.Models;
using EdgeOfTheEmpire.ViewModels;
using EdgeOfTheEmpire.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EdgeOfTheEmpire.Controllers
{
    public class SkillController : Controller
    {
        IStaticDataRepository staticDataRepository;
        public SkillController(IStaticDataRepository staticDataRepository)
        {
            this.staticDataRepository = staticDataRepository;
        }
        // GET: /<controller>/
        public IActionResult Index(string skill)
        {
            Skill theSkill = staticDataRepository.GetSkill(skill);
            IList<Career> careers = staticDataRepository.GetCareersWithSkill(theSkill);
            IList<Specialization> specializations = staticDataRepository.GetSpecializationsWithSkill(theSkill);
            var vm = new SkillViewModel() { Skill = theSkill, Careers = careers, Specializations = specializations };
            return View(vm);
        }
        public IActionResult List()
        {
            return View(staticDataRepository.GetSkills());
        }
    }
}

EdgeOfTheEmpire/Controllers/SpecializationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EdgeOfTheEmpire.Models;
using EdgeOfTheEmpire.ViewModels;
using EdgeOfTheEmpire.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EdgeOfTheEmpire.Controllers
{
    public class SpecializationController : Controller
    {
        private readonly IStaticDataRepository staticDataRepository;

        public SpecializationController(IStaticDataRepository staticDataRepository)
        {
            this.staticDataRepository = staticDataRepository;
        }

        // GET: /<controller>/
        public IActionResult Index(string specializationName)
        {
            Specialization specialization = staticDataRepository.GetSpecialization(specializationName);
            Career career = specialization.Career;
            IEnumerable<Skill> skills = staticDataRepository.GetSpecializationSkills(specialization);           
            TalentTree talentTree = staticDataRepository.GetSpecializationTalentTree(specialization);
            SpecializationInfoViewModel vm = new SpecializationInfoViewModel()
            {
                Career = career,
                Skills = skills,
                Specialization = specialization,
                TalentTree = talentTree
            };
            return View(vm);
        }

        public IActionResult List()
        {
            return View(staticDataRepository.GetSpecializations());
        }
    }
}

EdgeOfTheEmpire/Controllers/TalentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EdgeOfTheEmpire.Models;
using EdgeOfTheEmpire.ViewModels;
using EdgeOfTheEmpire.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EdgeOfTheEmpire.Controllers
{
    public class TalentController : Controller
    {
        private readonly IStaticDataRepository staticDataRepository;

        public TalentController(IStaticDataRepository staticDataRepository)
        {
            this.staticDataRepository = staticDataRepository;
        }

        // GET: /<controller>/
        public IActionResult Index(string talentName)
        {
            Talent talent = staticDataRepository.GetTalent(talentName);
            var specializations = staticDataRepository.GetSpecializationsWithTalent(talent);
            var vm = new TalentInfoViewModel() { Talent = talent, Specializations = specializations };
            return View(vm);
        }

        public IActionResult List()
        {
            return View(staticDataRepository.GetTalents());
        }
    }
}

EdgeOfTheEmpire/Views/Specialization/Index.cshtml
@model  EdgeOfTheEmpire.ViewModels.SpecializationInfoViewModel

<div class="container">
    <h2>@Model.Specialization.SpecializationName</h2>

    <div class="col-md-12">
        <div class="container">
            <h3>Skills</h3>
            <ul>
                @foreach (var skill in Model.Skills)
                {
                    <li>
                <a asp-controller="Skill" asp-action="Index" asp-route-skill="@skill.Name">@skill.Name</a>
                    </li>
                }
            </ul>

        </div>
    </div>

    <div class="container">
        <h3>Talents</h3>
        @foreach (var talent in Model.TalentTree.TalentTreeData.Values)
        {
            <div class="col-md-3">
                <div class="container">
                    <a asp-controller="Talent" asp-action="Index" asp-route-talentName="@talent.TalentName">@talent.TalentName</a>
                </div>
            </div>
        }


    </div>
    
</div>

EdgeOfTheEmpire/Views/Specialization/List.cshtml
@model IEnumerable<EdgeOfTheEmpire.Models.Specialization>

    @foreach (var specialization in Model)
    {
        <h2>
            <a asp-controller="Specialization" asp-action="Index" asp-route-specializationName="@specialization.SpecializationName">@specialization.SpecializationName</a>
        </h2>
    }